### ISSUE TITLE
飲み物どうするか

### ISSUE THREAD

**Issue by attsumi** [tamabi/tamabi.github.io#1]
何用意するか
ビールサーバーお願いするかどうか
カクヤスの配送とか検討しても良いかも

**Comment by shikakun** [comment]
尾山台のオオゼキで買っていきますか…！

**Comment by attsumi** [comment]
カクヤスに頼めるか検討中です！オオゼキもよさそう！

**Comment by attsumi** [comment]
## 飲み物買うもの
カクヤスで注文予定。
以下に配達していただく。

「玉堤一丁目」バス停に配達してもらった。
<s>セブンイレブン世田谷玉堤1丁目店
〒158-0087 東京都世田谷区玉堤１丁目２７−１５
https://goo.gl/maps/PdXvES7wvH22</s>

<s>- アサヒスーパードライの樽 10L</s>
<s>- ガスカードリッジ</s>
- オレンジジュース 1.5L
- お茶　2Lを2本。
- 氷 
- チューハイ6本くらい？
- オレンジジュース 1本

0409追記）お茶は2L 1本まるまる余った

**Comment by attsumi** [comment]
会費頂戴する感じにした方がいいかも。ひとり1000円くらい。

**Comment by attsumi** [comment]
飲み物はしかくんに追加で12本350mlスーパードライを買ってきていただいた。
あとは各人によしなに持ってきていただいた。
会費は1000円いただいた。余った分は二次会に回した。
