### ISSUE TITLE
食べ物どうするか

### ISSUE THREAD

**Issue by attsumi** [tamabi/tamabi.github.io#2]
軽くあると良さそう
おつまみてきなものとか？
ピザとか宅配してもらえたりしないか

**Comment by shikakun** [comment]
ここのパン全部うまいです。
https://tabelog.com/tokyo/A1317/A131715/13046641/

パンで酒は無理か〜〜〜

**Comment by attsumi** [comment]
パン情報ありがたい！！

**Comment by attsumi** [comment]
おつまみとかお菓子とか用意する
カクヤス荷物引取組で適当に買う感じで良さそう
