### ISSUE TITLE
持ち物

### ISSUE THREAD

**Issue by attsumi** [tamabi/tamabi.github.io#3]
とりあえずいりそうなものリストアップ
誰にお願いするかはあとで考える

- レジャーシート
- ごみぶくろ大きいやつ3,4枚
- ウェットティッシュ
- 栓抜き？

**Comment by shikakun** [comment]
前回の反省をふまえて、ゴミ袋とティッシュと栓抜き、あと割り箸はもっていきます！

**Comment by attsumi** [comment]
20人で集まるの大変そうなので目印など欲しい
「多摩ビ」って書いてある紙もっていく

**Comment by attsumi** [comment]
うどんちゃんが「多摩ビ」って書いてある紙を持ってきてくれた。
