### ISSUE TITLE
会場

### ISSUE THREAD

**Issue by attsumi** [tamabi/tamabi.github.io#4]
どこにするか

**Comment by attsumi** [comment]
会場予定だった多摩川河川敷、尾山台駅から20分かかった。駅から10分くらいで到着するイメージだった。。途中坂も挟むし、道も細いしで20人で歩いて移動するのはきついかも。他にも検討したい。

もし無理そうだったらタクシー移動かなあ。

**Comment by shikakun** [comment]
ワイン飲みながら歩きましょう

**Comment by shikakun** [comment]
大変かな… 二子玉川のほうが川近くていいのかなあ。
九品仏まで歩けば（10分ぐらい）浄真寺もありますね…（酒は飲めなさそう）

**Comment by attsumi** [comment]
@shikakun コメントありがとうございます！気づけば前日だったので予定していた尾山台駅から歩いて20分の、多摩川玉川公園付近でやりたいと思います！！

**Comment by attsumi** [comment]
Google Maps で現在地のリンクを送る機能？がかなり重宝した。
@shikakun 尾山台からのご案内ありがとうございました！

**Comment by shikakun** [comment]
Google マップの現在地を共有する機能、知らなかったけど便利でしたね…
こちらこそありがとうございました 🙏
